---
# tasks file for ansible-role-openbsd-bootstrap

- name: Install Python
  raw: "PKG_PATH={{ openbsd_pkg_mirror }}/OpenBSD/%c/packages/%a/ /usr/sbin/pkg_add -I py-pip"
  register: openbsd_pkg_add_python
  failed_when: "'error' in openbsd_pkg_add_python.stdout|lower"
  changed_when: "'py-pip' in openbsd_pkg_add_python.stdout"

- name: Symlink python
  raw: ln -fs /usr/local/bin/python2.7 /usr/bin/python
  changed_when: False # Can't tell if a change was made.
  tags:
      - skip_ansible_lint

- name: Gather facts
  setup:

- name: Configure pkg
  lineinfile:
    dest: /etc/pkg.conf
    line: 'installpath = {{ openbsd_pkg_mirror }}/OpenBSD/%c/packages/%a/'
    regexp: '^installpath ='
    state: present
    create: yes
