---
# tasks file for ansible-role-openbsd-bootstrap

- name: Install Python
  raw: "PKG_PATH={{ openbsd_pkg_mirror }}/OpenBSD/$(uname -r)/packages/$(arch -s)/ /usr/sbin/pkg_add -I py-pip"
  register: openbsd_pkg_add_python
  failed_when: "'error' in openbsd_pkg_add_python.stdout|lower"
  changed_when: "'py-pip' in openbsd_pkg_add_python.stdout"

- name: Symlink python
  raw: ln -s /usr/local/bin/python2.7 /usr/bin/python
  register: symlink_python
  changed_when: not 'File exists' in symlink_python.stdout
  failed_when: symlink_python|failed and not 'File exists' in symlink_python.stdout

- name: Gather facts
  setup:

- name: Configure pkg
  lineinfile:
    dest: /etc/pkg.conf
    line: 'installpath = {{ openbsd_pkg_mirror }}/OpenBSD/%v/packages/%a/'
    regexp: '^installpath ='
    state: present
    create: yes
