---
# tasks file for ansible-role-openbsd-bootstrap

- name: Install Python
  raw: "PKG_PATH={{ openbsd_pkg_mirror }}/OpenBSD/%c/packages/%a/ /usr/sbin/pkg_add -I py-pip"
  register: openbsd_pkg_add_python
  failed_when: "'error' in openbsd_pkg_add_python.stdout|lower"
  changed_when: "'py-pip' in openbsd_pkg_add_python.stdout"

- name: Gather facts
  setup:

- name: Symlink python
  file:
      path: /usr/bin/python
      src: /usr/local/bin/python2.7
      state: link
      owner: root
      group: 0
      mode: 0o0755

- name: Configure pkg
  lineinfile:
    dest: /etc/pkg.conf
    line: 'installpath = {{ openbsd_pkg_mirror }}/OpenBSD/%c/packages/%a/'
    regexp: '^installpath ='
    state: present
    create: yes
